kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
# 컨트롤 플레인
- role: control-plane
  extraPortMappings:
  - containerPort: 30080 #DevSecOps Web
    hostPort: 30080
    listenAddress: "0.0.0.0"
    protocol: TCP
  - containerPort: 30601 #Kibana
    hostPort: 30601
    listenAddress: "0.0.0.0"
    protocol: TCP

# 워커 노드 1: 웹서버
- role: worker
  labels:
    node-type: webserver
    purpose: apache-php

# 워커 노드 2: Jenkins
- role: worker
  labels:
    node-type: auto
    purpose: jenkins

# 워커 노드 3: 백업 DB
- role: worker
  labels:
    node-type: backup-db
    purpose: backup-storage

# 워커 노드 4: ELK
- role: worker
  labels:
    node-type: elk
    purpose: elk-stack

# 워커 노드 5: 로그 DB
- role: worker
  labels:
    node-type: log-db
    purpose: mariadb-logs

# 워커 노드 6: 웹 DB
- role: worker
  labels:
    node-type: web-db
    purpose: mariadb-web
