apiVersion: v1
kind: Service
metadata:
  name: wargame-web-service
  namespace: wargame
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080
  selector:
    app: wargame
---
apiVersion: v1
kind: Service
metadata:
  name: wargame-db-service
  namespace: wargame
spec:
  type: ClusterIP
  ports:
  - port: 3306
    targetPort: 3306
    protocol: TCP
  selector:
    app: wargame-db
---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-service
spec:
  type: NodePort
  selector:
    app: jenkins
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 32000
