apiVersion: apps/v1
kind: Deployment
metadata:
  name: wargame-deployment
  namespace: wargame
spec:
  selector:
    matchLabels:
      app: wargame
  template:
    metadata:
      labels:
        app: wargame
        node-type: webserver
    spec:
      containers:
      - env:
        - name: DB_HOST
          value: wargame-db-service
        - name: DB_PORT
          value: "3306"
        - name: DB_DATABASE
          value: LED_WG
        - name: DB_USERNAME
          value: wargame
        - name: DB_PASSWORD
          value: "1234"
        image: krjaeh0/wargame:latest
        imagePullPolicy: Always
        name: wargame
        ports:
        - containerPort: 80
      nodeSelector:
        node-type: webserver
